package slashcmd

type HelpEntry struct {
	Command     string
	Description string
}

func TUIHelpEntries() []HelpEntry {
	return []HelpEntry{
		{"/help", "show help"},
		{"/session", "show current session id"},
		{"/session <id>", "switch session id"},
		{"/api", "show websocket endpoint"},
		{"/api <ws-url>", "switch websocket endpoint"},
		{"/http", "show http api base"},
		{"/http <http-url>", "switch http api base"},
		{"/tools", "list tools"},
		{"/tool <name>", "show tool schema"},
		{"/sessions [n]", "list recent sessions"},
		{"/pick <index>", "switch session from last /sessions result"},
		{"/show [sid] [o] [l]", "show session messages"},
		{"/next", "show next page (based on last /show)"},
		{"/prev", "show previous page (based on last /show)"},
		{"/stats [sid]", "show session stats"},
		{"/targets [platform]", "list delivery targets"},
		{"/sethome <p:id>|<p> <id>", "set platform home target"},
		{"/gateway status", "show gateway status"},
		{"/gateway enable", "enable gateway"},
		{"/gateway disable", "disable gateway"},
		{"/config get", "show config snapshot"},
		{"/config set k v", "set config key/value"},
		{"/config tui", "show effective [ui-tui] config and source"},
		{"/pretty on|off", "enable/disable pretty json"},
		{"/view human|json", "switch display mode"},
		{"/last", "print last json payload"},
		{"/save <file>", "save last json payload"},
		{"/status", "show last command status"},
		{"/health", "check backend health endpoint"},
		{"/cancel", "cancel current session run"},
		{"/history [n]", "show local command history"},
		{"/timeline [n]", "show recent conversation timeline"},
		{"/rerun <index>", "rerun command from history"},
		{"/events [n]", "show recent runtime events"},
		{"/events save <file> [json|ndjson] [since=<RFC3339>] [until=<RFC3339>]", ""},
		{"/bookmark add <name>", "save current session/api profile"},
		{"/bookmark list", "list bookmarks"},
		{"/bookmark use <name>", "restore session/api profile"},
		{"/workbench save <name>", "save current workbench profile"},
		{"/workbench list", "list workbench profiles"},
		{"/workbench load <name>", "load workbench profile"},
		{"/workbench delete <name>", "delete workbench profile"},
		{"/workflow save <name> <cmd1;cmd2;...>", ""},
		{"/workflow list", ""},
		{"/workflow run <name> [dry]", ""},
		{"/workflow delete <name>", ""},
		{"/pending [n]", "show latest pending approval(s) in session"},
		{"/approve [id]", "approve pending approval id (default latest)"},
		{"/deny [id]", "deny pending approval id (default latest)"},
		{"/reload-config", "reload [ui-tui] config from config.ini"},
		{"/doctor", "run backend capability checks"},
		{"/actions", "open quick action palette"},
		{"/panel [name]", "switch fullscreen panel (overview/dashboard/sessions/tools/approvals/gateway/diag)"},
		{"/panel list", "list available fullscreen panels"},
		{"/panel next|prev", "cycle fullscreen panels"},
		{"/panel status", "show panel runtime status"},
		{"/panel auto on|off", "toggle panel auto refresh"},
		{"/panel interval <sec>", "set panel auto refresh interval"},
		{"/open <index>", "open item from current panel (sessions/tools/approvals)"},
		{"/refresh", "refresh current fullscreen panel data"},
		{"/version", "show ui-tui build metadata"},
		{"/reconnect status", "show reconnect status"},
		{"/reconnect on|off", "enable/disable auto reconnect"},
		{"/reconnect now", "probe websocket endpoint immediately"},
		{"/reconnect timeout wait|reconnect|cancel", ""},
		{"/recover context", "new session and retry last user message"},
		{"/diag", "show realtime diagnostics"},
		{"/diag export <file>", "export diagnostics bundle"},
		{"/fullscreen", "show fullscreen mode status"},
		{"/fullscreen on|off", "toggle fullscreen dashboard mode"},
		{"/quit", "exit"},
	}
}

func TUIRootCommands() []string {
	return []string{
		"/help", "/session", "/api", "/http", "/tools", "/tool", "/sessions", "/pick", "/show", "/next", "/prev",
		"/stats", "/targets", "/sethome", "/gateway", "/config", "/pretty", "/view", "/last", "/save", "/status", "/health", "/cancel",
		"/history", "/timeline", "/rerun", "/events", "/bookmark", "/workbench", "/workflow", "/pending",
		"/approve", "/deny", "/reload-config", "/doctor", "/actions", "/panel", "/open", "/refresh", "/version",
		"/reconnect", "/recover", "/diag", "/fullscreen", "/quit", "/exit", "/new", "/reset",
		"/stop",
	}
}

func CLIHelpLines() []string {
	return []string{
		"/help | /commands             显示命令帮助",
		"/status | /session            显示当前会话状态",
		"/new [session_id]             新建并切换会话",
		"/reset [session_id]           清空上下文并切换到新会话",
		"/resume <session_id>          切换并加载已有会话",
		"/retry                        重试上一条用户消息",
		"/undo                         从当前上下文撤销上一轮",
		"/compress [tail]              压缩当前上下文，保留最近 tail 条",
		"/save [path]                  导出当前上下文为 JSON",
		"/sethome <p> <id>|<p:id>      设置平台默认 home target",
		"/targets [platform]           列出已知可投递目标",
		"/history [n]                  预览最近 n 条上下文消息",
		"/sessions [n]                 列出最近 n 个会话",
		"/show [sid] [offset] [limit]  分页查看会话消息",
		"/stats [session_id]           查看会话统计",
		"/usage [session_id]           查看会话用量/统计",
		"/tools [list|show|schemas]    查看工具列表、单个 schema 或全部 schema",
		"/toolsets [list|show|resolve] 查看工具集",
		"/todo                         查看当前会话 todo",
		"/memory [memory|user]         查看持久记忆",
		"/model                        显示当前模型客户端",
		"/personality [show|reset|...] 查看或设置会话 system prompt",
		"/cancel | /stop               取消当前任务（若支持）",
		"/reload                       从存储重载当前会话",
		"/clear                        清空当前进程内上下文",
		"/tui                          显示 CLI/TUI 能力状态",
		"/quit | /exit                 退出会话",
	}
}
